### PR TITLE
Feature: Added Footer Section to the website.

### PR DESCRIPTION
**Pull request by CodeByRajeev**
This PR creates a footer section for the website as mentioned in the issue to add the required details:
- Contact Details
- Social Profiles
- Services, etc...

Fix **#5**

### CODE REVIEW

**Comment by neeraj542** [comment]
Add some screen previews (mobile responsive if possible)

**Comment by CodeByRajeev** [comment]
> This PR creates a footer section for the website as mentioned in the issue to add the required details:
> 
> * Contact Details
> * Social Profiles
> * Services, etc...
> 
> Fix **#5**

Screenshot (64)

**Comment by neeraj542** [comment]
Furthermore, please update the CSS to ensure that the design remains consistent with its current appearance. @CodeByRajeev

**Comment by Veerhan-glitch** [comment]
so if this is done should i leave out mine? (its not much different than what this pr has implemented)
alto @CodeByRajeev i will suggest use a background colour which matches the present ui better (like #0c0935)


What i have done for a reference:
Desktop:
image
Phone:
image

**Comment by neeraj542** [comment]
@CodeByRajeev @Veerhan-glitch need to design the footer page with social logos aligned with the universal color format of this website

**Comment by CodeByRajeev** [comment]
Feature #5: Added a Footer Section to the website.

As mentioned in the issue #5, the following has been added in the Footer Section:
- Footer Section ( Universal Colour of the website )
- Social Media Profiles
- Home
- About
- Services
- Terms
- Privacy Policy

If anything extra has to be added or removed in the footer section, can be easily done as everything in detail has been mentioned in the code alongside.

The footer section along with the website looks like this: 


Screenshot (66)

**Comment by CodeByRajeev** [comment]
Feature #5: Added a Footer Section to the website.

As mentioned in the issue #5 , the following has been added in the Footer Section:

Footer Section ( Universal Colour of the website )
Social Media Profiles
Home
About
Services
Terms
Privacy Policy
If anything extra has to be added or removed in the footer section, can be easily done as everything in detail has been mentioned in the code alongside.

The footer section along with the website looks like this:
WhatsApp Image 2023-10-03 at 23 06 56

**Pull request merged**
