### PR TITLE
Feature footer

### PR DESCRIPTION
**Pull request by Veerhan-glitch**
For #5 , THis is what i had done,
It works on bothphone and desktop
Screen Shot 2023-10-03 at 00 04 18
Screen Shot 2023-10-03 at 00 00 05

What hasn't been done: Making the links function (as i dont have ur scocial)

I have created this pr even after #6 ps was made as i was assigned to this issue and my version includes the requested feature in #6 (but feel free to close this if you aceept #6)

Let me know if you want me to add/change anything

### CODE REVIEW

**Comment by Veerhan-glitch** [comment]
Now everything works,my last few commits were to make sure it worked in each mobile size
pls scan the qr and tell if it works in your phone

**Comment by neeraj542** [comment]
Looking awesome 👍

**Review by neeraj542 — COMMENTED** [review]
Just add the relevant comments

**Review by neeraj542 — APPROVED** [review]

**Review by neeraj542 — APPROVED** [review]

**Comment by neeraj542** [comment]
Make sure you have followed all the color gradients which are used globally. @Veerhan-glitch

**Review by neeraj542 — APPROVED** [review]

**Comment by Veerhan-glitch** [comment]
@neeraj542 i have implemented the icons, pls tell if they are up to the mark

**Comment by Veerhan-glitch** [comment]
Hey, for the color gradient, I have used the oranged color for hover used in the header hover, and the only new color is of the header background, just tell me if u want it same is the pages background color

**Pull request closed without merging**
