### PR TITLE
Add export expense data feature  #10

### LINKED ISSUE #10: Add Expense Data Export Feature
**Issue Description:**

This is to propose adding an **Expense Export** feature to our finance tracker app. Users would benefit from the ability to export their expense data in formats like CSV or Excel, making it easier to:

- Keep offline records.
- Share data with financial advisors.
- Analyze expenses in their preferred tools.
- Create backups of their financial data.

This feature would enhance the app's usability and value.

Open for all contributors!

**For better understanding:** 

image

### PR DESCRIPTION
**Pull request by deeksharungta**
Added an export button which enables user to export their expense data in either .pdf or .csv format.
closes #10

### CODE REVIEW

**Comment by neeraj542** [comment]
**It's looking awesome 👍**

**Review by neeraj542 — CHANGES_REQUESTED** [review]
maximize the row size after adding more than 3 transactions as it automatically switch to scrollbar after adding 3 transactions.

**Comment by deeksharungta** [comment]
> maximize the row size after adding more than 3 transactions as it automatically switch to scrollbar after adding 3 transactions.

can you share the screenshot of the issue?

**Comment by neeraj542** [comment]
> > maximize the row size after adding more than 3 transactions as it automatically switch to scrollbar after adding 3 transactions.
> 
> can you share the screenshot of the issue?

no need to screenshot, just add the transactions more than 3 or 4

**Comment by deeksharungta** [comment]
> > > maximize the row size after adding more than 3 transactions as it automatically switch to scrollbar after adding 3 transactions.
> > 
> > 
> > can you share the screenshot of the issue?
> 
> no need to screenshot, just add the transactions more than 3 or 4

How many transactions do you prefer to be visible before transitioning to a scrollbar, or do you prefer not to display a scrollbar?

**Comment by neeraj542** [comment]
> > > > maximize the row size after adding more than 3 transactions as it automatically switch to scrollbar after adding 3 transactions.
> > > 
> > > 
> > > can you share the screenshot of the issue?
> > 
> > 
> > no need to screenshot, just add the transactions more than 3 or 4
> 
> How many transactions do you prefer to be visible before transitioning to a scrollbar, or do you prefer not to display a scrollbar?

It would be better to limit it to a maximum of 10 transactions, and please add a counter to keep track of the total number of transactions added at the bottom or wherever it looks fine.

**Comment by deeksharungta** [comment]
> > > > > maximize the row size after adding more than 3 transactions as it automatically switch to scrollbar after adding 3 transactions.
> > > > 
> > > > 
> > > > can you share the screenshot of the issue?
> > > 
> > > 
> > > no need to screenshot, just add the transactions more than 3 or 4
> > 
> > 
> > How many transactions do you prefer to be visible before transitioning to a scrollbar, or do you prefer not to display a scrollbar?
> 
> It would be better to limit it to a maximum of 10 transactions, and please add a counter to keep track of the total number of transactions added at the bottom or wherever it looks fine.

Would you mind creating a new issue for the scrollbar and counter, and assign it to me, so that it's kept separate from the current issue. Thank you!

**Comment by neeraj542** [comment]
> > > > > > maximize the row size after adding more than 3 transactions as it automatically switch to scrollbar after adding 3 transactions.
> > > > > 
> > > > > 
> > > > > can you share the screenshot of the issue?
> > > > 
> > > > 
> > > > no need to screenshot, just add the transactions more than 3 or 4
> > > 
> > > 
> > > How many transactions do you prefer to be visible before transitioning to a scrollbar, or do you prefer not to display a scrollbar?
> > 
> > 
> > It would be better to limit it to a maximum of 10 transactions, and please add a counter to keep track of the total number of transactions added at the bottom or wherever it looks fine.
> 
> Would you mind creating a new issue for the scrollbar and counter, and assign it to me, so that it's kept separate from the current issue. Thank you!

I don't have any issues, but this should be done first.

**Review by neeraj542 — APPROVED** [review]

**Comment by deeksharungta** [comment]
> > > > > > > maximize the row size after adding more than 3 transactions as it automatically switch to scrollbar after adding 3 transactions.
> > > > > > 
> > > > > > 
> > > > > > can you share the screenshot of the issue?
> > > > > 
> > > > > 
> > > > > no need to screenshot, just add the transactions more than 3 or 4
> > > > 
> > > > 
> > > > How many transactions do you prefer to be visible before transitioning to a scrollbar, or do you prefer not to display a scrollbar?
> > > 
> > > 
> > > It would be better to limit it to a maximum of 10 transactions, and please add a counter to keep track of the total number of transactions added at the bottom or wherever it looks fine.
> > 
> > 
> > Would you mind creating a new issue for the scrollbar and counter, and assign it to me, so that it's kept separate from the current issue. Thank you!
> 
> I don't have any issues, but this should be done first.

yes, sure!

**Pull request merged**
